require('dotenv').config();

const express = require('express');
const axios = require('axios');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Paths and Storage
const DIALOGUES_FILE = path.join(__dirname, 'dialogues.json');

// Load dialogues & default description data
let dialogues = [];
let defaultDescription = "Activity name auto generated by BandookDotCom - give your activities the names they need, but maybe not deserve";

// Load the dialogues from JSON file (sync on startup)
function loadDialogues() {
  try {
    const data = fs.readFileSync(DIALOGUES_FILE, 'utf-8');
    dialogues = JSON.parse(data);
    console.log(`Loaded ${dialogues.length} dialogues`);
  } catch (err) {
    console.error('Failed to load dialogues file:', err);
    dialogues = [];
  }
}
// Save dialogues back to JSON file
function saveDialogues() {
  try {
    fs.writeFileSync(DIALOGUES_FILE, JSON.stringify(dialogues, null, 2), 'utf-8');
  } catch (err) {
    console.error('Failed to save dialogues:', err);
  }
}

loadDialogues();

// List of common default/generic activity names to catch for auto-renaming
const defaultActivityNames = [
  "Morning Run",
  "Evening Run",
  "Run",
  "Workout",
  "Ride",
  "Evening Ride",
  "Afternoon Run",
  "Afternoon Ride",
  "Run Endurance",
  "Race",
  "Training",
  "Long Ride",
];

// -------- Routes --------

// 1. OAuth Token Exchange
app.post('/api/token', async (req, res) => {
  try {
    const { code } = req.body;
    if (!code) return res.status(400).json({ error: "Authorization code is required" });

    const response = await axios.post('https://www.strava.com/oauth/token', {
      client_id: process.env.STRAVA_CLIENT_ID,
      client_secret: process.env.STRAVA_CLIENT_SECRET,
      code,
      grant_type: 'authorization_code',
    });

    res.json(response.data);
  } catch (e) {
    console.error("Error in /api/token:", e.response?.data || e.message);
    res.status(500).json({ error: e.response?.data || e.message });
  }
});

// 2. Fetch Activities
app.get('/api/activities', async (req, res) => {
  try {
    const { token } = req.query;
    if (!token) return res.status(400).json({ error: "Access token is required" });

    const response = await axios.get('https://www.strava.com/api/v3/athlete/activities', {
      headers: { Authorization: `Bearer ${token}` },
    });

    res.json(response.data);
  } catch (e) {
    console.error("Error in /api/activities:", e.response?.data || e.message);
    res.status(500).json({ error: e.response?.data || e.message });
  }
});

// 3. Rename Activity (manual)
app.put('/api/rename', async (req, res) => {
  try {
    const { token, activityId } = req.body;
    if (!token || !activityId) return res.status(400).json({ error: "Access token and activityId required" });

    if (dialogues.length === 0) return res.status(500).json({ error: "No dialogues available" });

    const d = dialogues[Math.floor(Math.random() * dialogues.length)];
    const name = d.dialogue;
    const description = `— ${d.movie} (${d.year})\n${defaultDescription}`;

    const response = await axios.put(
      `https://www.strava.com/api/v3/activities/${activityId}`,
      { name, description },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    res.json(response.data);
  } catch (e) {
    console.error("Error in /api/rename:", e.response?.data || e.message);
    res.status(500).json({ error: e.response?.data || e.message });
  }
});

// 4. Add New Dialogue
app.post('/api/add-dialogue', (req, res) => {
  const { dialogue, movie, year } = req.body;

  if (!dialogue || !dialogue.trim()) return res.status(400).json({ error: "Dialogue text is required" });
  if (!movie || !movie.trim()) return res.status(400).json({ error: "Movie name is required" });
  if (!year || !Number.isInteger(year)) return res.status(400).json({ error: "Valid release year is required (integer)" });

  const exists = dialogues.find(
    (d) => d.dialogue.toLowerCase() === dialogue.trim().toLowerCase()
  );

  if (exists) return res.status(409).json({ error: "Dialogue already exists" });

  const newEntry = {
    dialogue: dialogue.trim(),
    movie: movie.trim(),
    year
  };

  dialogues.push(newEntry);
  saveDialogues();

  res.json({ success: true, dialogue: newEntry, totalDialogues: dialogues.length });
});

// 5. Get Default Description
app.get('/api/default-description', (req, res) => {
  res.json({ description: defaultDescription });
});

// 6. Update Default Description
app.post('/api/update-description', (req, res) => {
  const { description } = req.body;
  if (!description || !description.trim()) return res.status(400).json({ error: "Description text is required" });

  defaultDescription = description.trim();
  res.json({ success: true, description: defaultDescription });
});

// 7. Auto Rename Recent Activities (manual trigger)
app.post('/api/auto-rename', async (req, res) => {
  try {
    const { token } = req.body;
    if (!token) return res.status(400).json({ error: "Access token required" });

    const activitiesRes = await axios.get(
      'https://www.strava.com/api/v3/athlete/activities',
      { headers: { Authorization: `Bearer ${token}` }, params: { per_page: 30 } }
    );

    const activities = activitiesRes.data;
    const renamedActivities = [];

    for (const activity of activities) {
      if (defaultActivityNames.includes(activity.name)) {
        if (dialogues.length === 0) continue;

        const d = dialogues[Math.floor(Math.random() * dialogues.length)];
        const name = d.dialogue;
        const description = `— ${d.movie} (${d.year})\n${defaultDescription}`;

        await axios.put(
          `https://www.strava.com/api/v3/activities/${activity.id}`,
          { name, description },
          { headers: { Authorization: `Bearer ${token}` } }
        );

        renamedActivities.push({ id: activity.id, oldName: activity.name, newName: name });
      }
    }

    res.json({ success: true, renamed: renamedActivities });
  } catch (e) {
    console.error("Error in /api/auto-rename:", e.response?.data || e.message);
    res.status(500).json({ error: e.response?.data || e.message });
  }
});

// 8. Strava Webhook GET Endpoint - for subscription verification
app.get('/webhook', (req, res) => {
  const mode = req.query['hub.mode'];
  const token = req.query['hub.verify_token'];
  const challenge = req.query['hub.challenge'];

  const VERIFY_TOKEN = process.env.VERIFY_TOKEN || 'your_secret_verify_token'; // set in .env

  if (mode === 'subscribe' && token === VERIFY_TOKEN) {
    console.log(`Webhook verified with challenge: ${challenge}`);
    res.status(200).send(challenge);
  } else {
    console.warn('Webhook verification failed due to bad token or mode');
    res.status(403).send('Forbidden');
  }
});

// 9. Strava Webhook POST Endpoint - receive activity creation events for auto-renaming
app.post('/webhook', async (req, res) => {
  res.status(200).send('EVENT_RECEIVED'); // Reply immediately to Strava

  const { aspect_type, object_type, object_id, owner_id } = req.body;

  // For single user auto-renaming - put your athlete ID & access token in .env
  const yourAthleteId = Number(process.env.STRAVA_ATHLETE_ID);
  const token = process.env.STRAVA_ACCESS_TOKEN;

  if (object_type === 'activity' && aspect_type === 'create') {
    if (Number(owner_id) !== yourAthleteId) {
      // This webhook is for another user - ignore
      return;
    }

    try {
      // Fetch the activity to get name
      const activityRes = await axios.get(
        `https://www.strava.com/api/v3/activities/${object_id}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      const activity = activityRes.data;

      if (defaultActivityNames.includes(activity.name)) {
        if (dialogues.length === 0) return;

        const d = dialogues[Math.floor(Math.random() * dialogues.length)];
        const name = d.dialogue;
        const description = `— ${d.movie} (${d.year})\n${defaultDescription}`;

        await axios.put(
          `https://www.strava.com/api/v3/activities/${object_id}`,
          { name, description },
          { headers: { Authorization: `Bearer ${token}` } }
        );

        console.log(`Auto-renamed new activity ${object_id} from "${activity.name}" to "${name}".`);
      }
    } catch (err) {
      console.error("Error auto-renaming webhook activity:", err.response?.data || err.message);
    }
  }
});

// Server listen
app.listen(PORT, '0.0.0.0', () => {
  console.log(`Server listening on port ${PORT}`);
});
